#!/bin/bash

echo "🔍 Running pre-push checks..."

if git stash --keep-index; then
  trap "git stash pop" EXIT
fi

function fail() {
  echo -e "${RED}❌ $1${NC}"
  exit 1
}

echo "🔧 Running tests..."
./mvnw verify
if [ $? -ne 0 ]; then
  fail "There were test failures."
fi

echo "✅ All pre-push checks passed."
